import './globals.css';

import { Roboto } from 'next/font/google';
import { QueryProvider } from '@/providers/react-query-provider';
import { ThemeProvider } from '@/providers/theme-provider';

const roboto = Roboto({
  weight: ['400', '700'],
  subsets: ['vietnamese'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${roboto.className} antialiased`}>
        <QueryProvider>
          <ThemeProvider>{children}</ThemeProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
